### ISSUE TITLE
included columns

### ISSUE THREAD

**Issue by jimmymain** [mj1856/EntityFramework.IndexingExtensions#3]
Hi,

Is there any way to provide additional columns that would form part of the SQL INCLUDE clause?
as in:

```
CREATE NONCLUSTERED INDEX IX_Index
ON [schema].[Table] ([FieldA],[FieldB])
INCLUDE ([FieldX], [FieldY])
```

Thanks.

**Comment by mattjohnsonpint** [comment]
As far as I am aware, that isn't supported by EF yet.   All this extension really does is fluently add the `[Index]` attributes, so we're constrained by what they support.

The only way I know of to handle this is by writing your own index creation statements in EF Migrations, as [described here](http://stackoverflow.com/questions/22033866/entity-framework-6-1-create-index-with-include-statement).

**Comment by jimmymain** [comment]
thanks!
