### ISSUE TITLE
index migrations seem to disappear

### ISSUE THREAD

**Issue by ariovistus** [mj1856/EntityFramework.IndexingExtensions#4]
I have an entity class with many indexes. abbreviated, it looks something like this:

```
public partial class TABLE
{
    private const string Index5201 = "idx_TABLE_6_618341863__K2_K8_K1_K5_5201";
    private const string Index4864 = "idx_TABLE_6_618341863__K3_K4_K11_K2_K8_K1_4864";
    private const string Index8066 = "idx_TABLE_6_618341863__K4_K11_K3_K1_K2_K8_8066";
    private const string IndexSrl = "idx_TABLE_6_618341863__K4_K8_K3_10";
    private const string Index1410 = "idx_TABLE_6_618341863__K8_K1_K5_3_4_1410";
    ...

    [Key]
    [DatabaseGenerated(DatabaseGeneratedOption.None)]
    [Index(Index5201, order: 2)]
    [Index(Index4864, order: 5)]
    [Index(Index8066, order: 3)]
    [Index(Index1410, order: 1)]
    public int K1 { get; set; }

        ...
```

add-migration generates a migration for it that has the expected create index statements:

```
DropIndex("dbo.TABLE", new[] { "K2", "K3", "K4" });
DropIndex("dbo.TABLE", new[] { "K5" });
DropIndex("dbo.TABLE", new[] { "K10" });
DropIndex("dbo.TABLE", new[] { "K12" });
CreateIndex("dbo.TABLE", new[] { "K2", "K8", "K1", "K5" }, name: "idx_TABLE_6_618341863__K2_K8_K1_K5_5201");
CreateIndex("dbo.TABLE", new[] { "K3", "K4", "K11", "K2", "K8", "K1" }, name: "idx_TABLE_6_618341863__K3_K4_K11_K2_K8_K1_4864");
CreateIndex("dbo.TABLE", new[] { "K4", "K11", "K3", "K1", "K8" }, name: "idx_TABLE_6_618341863__K4_K11_K3_K1_K2_K8_8066");
...
```

However, when I replace one of the annotation-defined indexes with HasIndex:

```
modelBuilder.Entity<TABLE>()
    .HasIndex("idx_TABLE_8_618341863__K2_K8_K1_K4_K11_K5_K12_K10_K3_K6",
        e => e.Property(x => x.K2),
        e => e.Property(x => x.K8),
        ...
    );
```

and re-scaffold the migration, the new migration has a CreateIndex stmt for the index specified by HasIndex, and exactly one of the annotation-specified indexes. It omits all the other indexes.

For my purposes, this isn't a big deal since I don't want to keep the annotation indexes anyways, but why does it do this?

**Comment by mattjohnsonpint** [comment]
Sounds like the same issue as #2 ?   If you're using version 1.0, try 1.0.1 which has that fixed.

**Comment by ariovistus** [comment]
I was using 1.0.1

**Comment by mattjohnsonpint** [comment]
Hmmm.. Ok, good to know.  I will investigate when I have some time.

In general though, recognize that these extensions just manipulate the API that EF provides (using the `IndexAttribute` and `IndexAnnotation` classes).  I can fix it when we're not applying them properly, but if EF isn't using _those_ properly I can't do anything about it.
